version: "3"

services:
  app:
    container_name: application
    build: .
    ports:
      - 3000:3000 # nestjs server
      - 5555:5555 # prisma studio
    volumes:
      - .:/home/node/app
    networks:
      - fcexperience

  mongodb:
    container_name: mongodb
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - fcexperience

networks:
  fcexperience:
    external: true
## extra_hosts: "host.docker.internal:172.17.0.1"
# Linux or Mac
# /etc/hosts
# 127.0.0.1 host.docker.internal

# Windows
# C:\Windows\system32\drivers\etc\hosts
# 127.0.0.1 host.docker.internal
