version: '3'

services:
  # app:
  #   container_name: application
  #   build: .
  #   ports:
  #     - 3000:3000
  #     - 5555:5555
  #   volumes:
  #     - .:/home/node/app

  mongodb:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'

# volumes:
#   mongodb_data:
#     driver: local
# networks:
#   fcexperience:
#     external: true

# Linux or Mac
# /etc/hosts
# 127.0.0.1 host.docker.internal
